"use client";

import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { GraduationCap, Mail, ArrowRight, CheckCircle, KeyRound, ArrowLeft } from "lucide-react";
import { useAuthStore } from "@/store/authStore";

export default function ForgotPasswordPage() {
  const router = useRouter();
  const forgotPassword = useAuthStore((s) => s.forgotPassword);

  const [email, setEmail] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [successMsg, setSuccessMsg] = useState("");
  const [devResetToken, setDevResetToken] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMsg("");
    setSuccessMsg("");
    setDevResetToken(null);
    setIsLoading(true);

    const result = await forgotPassword(email);
    setIsLoading(false);

    if (!result.success) {
      setErrorMsg(result.error || "Failed to process request.");
      return;
    }

    setSuccessMsg(result.message || "Password reset instructions sent.");
    if (result.resetToken) {
      setDevResetToken(result.resetToken);
    }
  };

  return (
    <div className="min-h-screen bg-[#0b1226] flex items-center justify-center p-4 relative overflow-hidden">
      <div className="absolute -top-32 -left-32 w-96 h-96 bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute -bottom-32 -right-32 w-96 h-96 bg-gold/10 rounded-full blur-3xl pointer-events-none" />

      <div className="w-full max-w-md relative z-10">
        <div className="text-center mb-8">
          <Link href="/" className="inline-flex items-center gap-3 group mb-4">
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-primary to-[#1d3bb5] text-white shadow-lg shadow-primary/30">
              <GraduationCap className="h-6 w-6 transition-transform group-hover:scale-110" />
            </div>
            <div className="text-left">
              <span className="block font-display text-xl font-bold tracking-tight text-white">
                EduSphere
              </span>
              <span className="block text-[11px] font-semibold tracking-widest text-gold uppercase -mt-1">
                Institutional SaaS
              </span>
            </div>
          </Link>
          <h1 className="text-2xl font-display font-bold text-white tracking-tight">
            Forgot Password
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Enter your email to receive password reset instructions
          </p>
        </div>

        <div className="bg-white rounded-2xl p-8 shadow-2xl border border-slate-100">
          {errorMsg && (
            <div className="mb-4 rounded-lg bg-red-50 border border-red-200 px-3.5 py-2.5 text-xs font-medium text-red-600 flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-red-500 shrink-0" />
              {errorMsg}
            </div>
          )}

          {successMsg ? (
            <div className="space-y-4">
              <div className="rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-xs text-emerald-800 space-y-2">
                <div className="flex items-center gap-2 font-bold text-emerald-900">
                  <CheckCircle className="h-5 w-5 text-emerald-600" />
                  <span>Request Processed</span>
                </div>
                <p>{successMsg}</p>
              </div>

              {devResetToken && (
                <div className="rounded-xl bg-slate-900 p-4 border border-slate-800 text-slate-200 space-y-3">
                  <div className="flex items-center gap-2 text-xs font-bold text-gold uppercase tracking-wider">
                    <KeyRound className="h-4 w-4" />
                    <span>Dev Mode Shortcut</span>
                  </div>
                  <p className="text-[11px] text-slate-400">
                    A reset token was generated by the backend API:
                  </p>
                  <code className="block bg-slate-950 px-3 py-2 rounded-lg text-[11px] text-emerald-400 font-mono break-all select-all border border-slate-800">
                    {devResetToken}
                  </code>
                  <Link
                    href={`/reset-password?token=${devResetToken}`}
                    className="block w-full text-center bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs py-2.5 px-4 rounded-lg transition-colors"
                  >
                    Proceed to Reset Password →
                  </Link>
                </div>
              )}

              <div className="pt-2 text-center">
                <Link
                  href="/login"
                  className="inline-flex items-center gap-1.5 text-xs text-primary font-bold hover:underline"
                >
                  <ArrowLeft className="h-3.5 w-3.5" />
                  Back to Sign In
                </Link>
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1.5 uppercase tracking-wider">
                  Registered Email Address
                </label>
                <div className="relative">
                  <Mail className="absolute left-3.5 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
                  <input
                    type="email"
                    required
                    placeholder="admin.imed@punecollege.com"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full pl-10 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-xl text-xs text-slate-900 focus:outline-none focus:border-primary focus:bg-white transition-all"
                  />
                </div>
              </div>

              <button
                type="submit"
                disabled={isLoading}
                className="w-full bg-[#0f1a3a] text-white font-bold text-xs py-3.5 px-4 rounded-xl hover:bg-primary transition-all shadow-md flex items-center justify-center gap-2 group disabled:opacity-70 cursor-pointer"
              >
                {isLoading ? (
                  <span className="h-4 w-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    Send Reset Instructions
                    <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
                  </>
                )}
              </button>

              <div className="pt-3 text-center border-t border-slate-100">
                <Link
                  href="/login"
                  className="inline-flex items-center gap-1.5 text-xs text-slate-500 font-medium hover:text-primary transition-colors"
                >
                  <ArrowLeft className="h-3.5 w-3.5" />
                  Return to Login
                </Link>
              </div>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
