import { Wallet, Clock3, Users2, TrendingUp } from "lucide-react";

export const feeStatsPrincipal = [
  {
    label: "Collected Fees",
    value: "₹1,24,56,800",
    change: "12.5% from last month",
    trend: "up",
    icon: Wallet,
    tone: "violet",
  },
  {
    label: "Pending Fees",
    value: "₹18,76,400",
    change: "8.2% from last month",
    trend: "down",
    icon: Clock3,
    tone: "orange",
  },
  {
    label: "Total Students",
    value: "1,248",
    change: "3.4% from last month",
    trend: "up",
    icon: Users2,
    tone: "blue",
  },
  {
    label: "Collection Rate",
    value: "87.6%",
    change: "5.6% from last month",
    trend: "up",
    icon: TrendingUp,
    tone: "green",
  },
];

// Options for the Class & Section filter dropdown
export const classOptions = [
  { value: "ALL", label: "All Classes & Sections" },
  { value: "10-A", label: "Class 10 - A" },
  { value: "10-B", label: "Class 10 - B" },
  { value: "9-A", label: "Class 9 - A" },
  { value: "9-B", label: "Class 9 - B" },
  { value: "8-A", label: "Class 8 - A" },
];

// Options for the Fee Category filter dropdown.
// A student "matches" a category if any line in their fee breakdown
// mentions it — see the matchesFeeCategory check in page.jsx.
export const feeCategoryOptions = [
  { value: "ALL", label: "All Fee Types" },
  { value: "tuition", label: "Tuition Fees" },
  { value: "transport", label: "Transport Fees" },
  { value: "exam", label: "Exam Fees" },
];

export const studentsList = [
  {
    id: "ADM2024001",
    name: "Aarav Sharma",
    rollNo: "101",
    class: "10-A",
    totalFees: 25000,
    paidAmount: 20000,
    pendingAmount: 5000,
    status: "Partial Paid",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    guardianName: "Rajesh Sharma",
    phone: "+91 98765 43210",
    email: "aarav.sharma@example.com",
    address: "123, Green Park, Delhi - 110016",
    breakdown: [
      { particular: "Tuition Fees", amount: 12000 },
      { particular: "Transport Fees", amount: 4000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Activity Fees", amount: 1000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 3000 },
    ],
  },
  {
    id: "ADM2024002",
    name: "Diya Patel",
    rollNo: "102",
    class: "10-A",
    totalFees: 25000,
    paidAmount: 25000,
    pendingAmount: 0,
    status: "Paid",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    guardianName: "Sanjay Patel",
    phone: "+91 98765 11223",
    email: "diya.patel@example.com",
    address: "45, MG Road, Ahmedabad - 380001",
    breakdown: [
      { particular: "Tuition Fees", amount: 12000 },
      { particular: "Transport Fees", amount: 4000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Activity Fees", amount: 1000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 3000 },
    ],
  },
  {
    id: "ADM2024003",
    name: "Mayur Verma",
    rollNo: "103",
    class: "10-B",
    totalFees: 25000,
    paidAmount: 10000,
    pendingAmount: 15000,
    status: "Pending",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    guardianName: "Alok Verma",
    phone: "+91 98765 99887",
    email: "rohan.v@example.com",
    address: "78, Civil Lines, Jaipur - 302001",
    breakdown: [
      { particular: "Tuition Fees", amount: 12000 },
      { particular: "Transport Fees", amount: 4000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Activity Fees", amount: 1000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 3000 },
    ],
  },
  {
    id: "ADM2024004",
    name: "Ananya Singh",
    rollNo: "104",
    class: "9-A",
    totalFees: 22000,
    paidAmount: 22000,
    pendingAmount: 0,
    status: "Paid",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    guardianName: "Vikram Singh",
    phone: "+91 98765 33445",
    email: "ananya.s@example.com",
    address: "12, Park Street, Kolkata - 700016",
    breakdown: [
      { particular: "Tuition Fees", amount: 11000 },
      { particular: "Transport Fees", amount: 4000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 2000 },
    ],
  },
  {
    id: "ADM2024005",
    name: "Kabir Joshi",
    rollNo: "105",
    class: "9-B",
    totalFees: 22000,
    paidAmount: 12000,
    pendingAmount: 10000,
    status: "Partial Paid",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    guardianName: "Nikhil Joshi",
    phone: "+91 98765 55667",
    email: "kabir.j@example.com",
    address: "89, Bandra West, Mumbai - 400050",
    breakdown: [
      { particular: "Tuition Fees", amount: 11000 },
      { particular: "Transport Fees", amount: 4000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 2000 },
    ],
  },
  {
    id: "ADM2024006",
    name: "Meera Iyer",
    rollNo: "106",
    class: "8-A",
    totalFees: 20000,
    paidAmount: 0,
    pendingAmount: 20000,
    status: "Pending",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    guardianName: "Ramesh Iyer",
    phone: "+91 98765 77889",
    email: "meera.i@example.com",
    address: "56, Indiranagar, Bengaluru - 560038",
    breakdown: [
      { particular: "Tuition Fees", amount: 10000 },
      { particular: "Transport Fees", amount: 3000 },
      { particular: "Library Fees", amount: 1000 },
      { particular: "Lab Fees", amount: 2000 },
      { particular: "Exam Fees", amount: 2000 },
      { particular: "Development Fees", amount: 2000 },
    ],
  },
];

export const studentTransactions = [
  { title: "Tuition Fees", date: "Paid on 10 Apr 2025", amount: "₹12,000", status: "Success" },
  { title: "Transport Fees", date: "Paid on 10 Apr 2025", amount: "₹4,000", status: "Success" },
  { title: "Library Fees", date: "Paid on 10 Apr 2025", amount: "₹1,000", status: "Success" },
  { title: "Lab Fees", date: "Due on 31 May 2025", amount: "₹2,000", status: "Pending" },
  { title: "Exam Fees", date: "Due on 31 May 2025", amount: "₹2,000", status: "Pending" },
];
